// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-KX9WFRpWj67DAfihLrLE7R2bECeZB5Y',
    appId: '1:331557664849:web:19d937525a98e1f568e070',
    messagingSenderId: '331557664849',
    projectId: 'infinity-pioneers',
    authDomain: 'infinity-pioneers.firebaseapp.com',
    storageBucket: 'infinity-pioneers.firebasestorage.app',
    measurementId: 'G-V7ZT0E5Y0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8SbKliLRTy4fHJJuEGBVeDU4OgLFCqGA',
    appId: '1:331557664849:android:927ac36ad6d8258568e070',
    messagingSenderId: '331557664849',
    projectId: 'infinity-pioneers',
    storageBucket: 'infinity-pioneers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttodlWkczmTXIAOoDvc7jDAspup1Gn_o',
    appId: '1:331557664849:ios:6e8a2da7af5379cd68e070',
    messagingSenderId: '331557664849',
    projectId: 'infinity-pioneers',
    storageBucket: 'infinity-pioneers.firebasestorage.app',
    androidClientId: '331557664849-h3o66q03eiasuncjgvfbsk9vmmgpubjf.apps.googleusercontent.com',
    iosClientId: '331557664849-joj9slk73vrgj6071hrkrq18sc8nk6qa.apps.googleusercontent.com',
    iosBundleId: 'com.example.a3certify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttodlWkczmTXIAOoDvc7jDAspup1Gn_o',
    appId: '1:331557664849:ios:6e8a2da7af5379cd68e070',
    messagingSenderId: '331557664849',
    projectId: 'infinity-pioneers',
    storageBucket: 'infinity-pioneers.appspot.com',
    iosBundleId: 'com.example.a3certify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-KX9WFRpWj67DAfihLrLE7R2bECeZB5Y',
    appId: '1:331557664849:web:b16762fd1f05ec1f68e070',
    messagingSenderId: '331557664849',
    projectId: 'infinity-pioneers',
    authDomain: 'infinity-pioneers.firebaseapp.com',
    storageBucket: 'infinity-pioneers.firebasestorage.app',
    measurementId: 'G-ZKXF2XFGFV',
  );

}